
replicaCount: 1

image:
 
  repository: file-explorer-api
  tag: "local"
  
  pullPolicy: Never


config:
 
  backendType: "local"
  
  local:
    
    storageRootPath: "/data"
  
  s3:
    
    bucketName: "file-explorer"
    
    endpointUrl: "http://minio.default.svc.cluster.local:9000"
    
    credentialsSecret:
      name: "minio-credentials"
      accessKeyIdKey: "accessKey"
      secretAccessKeyKey: "secretKey"


persistence:
  enabled: false
 
  hostPath:
    path: /data/my-files
    type: DirectoryOrCreate

service:
  type: ClusterIP
  port: 80


monitoring:
  enabled: true