{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-file-explorer-sm
  labels:
    # This label is important! The default prometheus instance looks for this.
    release: prometheus
spec:
  selector:
    matchLabels:
      app: file-explorer
      release: {{ .Release.Name }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}