apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-file-explorer-svc
  labels:
    app: file-explorer
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: file-explorer
    release: {{ .Release.Name }}